### ISSUE TITLE
Add some docs?

### ISSUE THREAD

**Issue by joscha** [saymedia/terraform-buildkite#2]
would love to use this extension, however I am not completely sure on what the configuration looks like and which settings are supported. Is there any documentation that you can add to the `.md` file?
Some samples would be awesome!
Also, is it possible to import existing pipelines and then manage them with this module?

**Comment by apparentlymart** [comment]
Hi @joscha!

Sorry for the lack of docs here. We developed this primarily for internal use and shared it in the hope of it being useful, but haven't invested too much time in making it consumable.

For the moment I can just give you some pointers to get started.

The only resource in this provider is `buildkite_pipeline` and you can see [its arguments and attributes in code form](https://github.com/saymedia/terraform-buildkite/blob/a922a5435035b8ad6e99a7261fcb8dd26868ffa5/buildkite/resource_pipeline.go#L14). Hopefully the names are similar enough to what you can see in the [Buildkite API](https://buildkite.com/docs/rest-api/pipelines#create-a-pipeline) that it's understandable what these mean. The ones that say `Computed: true` are ones that would appear under "Exported Attributes" if this were in the Terraform manual, while `Required: true` and `Optional: true` represent the arguments.

We wrote this before Terraform had import functionality, so it's lacking support for the import feature. [The old manual approaches](https://dark.ca/2015/01/27/handling-extant-resources-in-terraform/) are therefore required here. If you follow those instructions, know that the "id" if the pipeline resource is the pipeline's slug.

I'll leave this issue open as a reminder to us to write some docs for this eventually. Hopefully the above notes are useful in the mean time.

**Comment by joscha** [comment]
Thanks @apparentlymart - sorry if that's an obvious question, but how do you guys install this provider on your CI - I tried
```bash
go get github.com/saymedia/terraform-buildkite/terraform-provider-buildkite
PATH="$HOME/go/bin:$PATH" terraform plan
```
but I get:
```
Error asking for user input: 1 error(s) occurred:

* buildkite_pipeline.test: provider buildkite couldn't be found
```
but terraform doesn't recognize it. Do I have to check out the gh-repo, build it in there and add it to the path?

EDIT: if I copy it to CWD it works, e.g. `cp $HOME/go/bin/terraform-provider-buildkite .` - not sure that's the best way to do it though.

**Comment by apparentlymart** [comment]
Hi @joscha,

If you run the command `go install github.com/saymedia/terraform-buildkite/terraform-provider-buildkite` you should get a program `terraform-provider-buildkite` in `$GOPATH/bin`. You have a couple different options for installing that so Terraform can find it:

* Put it in the same directory as the `terraform` program itself.
* Create [a `.terraformrc` file](https://www.terraform.io/docs/plugins/basics.html#installing-a-plugin) in your home directory (or, in CI, the home directory of whatever user runs `terraform`) that tells Terraform where to find the program.

As an example of the latter:

```hcl
providers {
  buildkite = "/usr/local/bin/terraform-providers-buildkite"
}
```

In our case at Say Media we just have `terraform` and the plugins (including this one) installed in the same directory on our system and put that directory in the `PATH` so our CI jobs can find it.

**Comment by joscha** [comment]
awesome, that's much better than the `cp`, thank you!

**Comment by joscha** [comment]
opened #5 which contains a simple README - will add more info as I go.
